/* main.js — Composition root: loads every module, hands the real handlers to the bootstrap stubs, then starts auth. */

import { auth, onAuthStateChanged } from './core/firebase.js';
import { handleAuthStateChange } from './auth/auth.js';


/* Every module below registers its window.* handlers when it loads. Order = original load order. */
import './core/firebase.js';
import './core/config.js';
import './core/utils.js';
import './core/icons.js';
import './core/state.js';
import './core/listeners.js';
import './auth/auth.js';
import './auth/superadmin-auth.js';
import './core/error-log.js';
import './ui/routing.js';
import './data/app-config.js';
import './data/permissions.js';
import './data/templates.js';
import './features/task-editor.js';
import './data/product-model.js';
import './core/gas.js';
import './features/dependency-map.js';
import './data/status.js';
import './views/dashboard.js';
import './data/products-cache.js';
import './views/workload.js';
import './views/myactions.js';
import './views/decisions.js';
import './ui/global-search.js';
import './ui/undo.js';
import './views/products.js';
import './features/product-form.js';
import './features/image-picker.js';
import './features/import-tasks.js';
import './features/ai.js';
import './views/drilldown.js';
import './views/project-dashboard.js';
import './features/export-sheet.js';
import './views/ask.js';
import './features/task-list-controls.js';
import './features/task-detail.js';
import './features/product-onboarding.js';
import './views/product-detail.js';
import './features/task-actions.js';
import './features/email-log.js';
import './features/comments.js';
import './views/calendar.js';
import './views/tracker.js';
import './views/documents.js';
import './views/reports.js';
import './views/settings.js';
import './features/readonly-portfolio.js';
import './auth/privacy-lock.js';
import './ui/shell.js';
import './features/share.js';
import './features/weekly-log.js';
import './features/handover.js';
import './superadmin/index.js';
import './superadmin/health.js';
import './superadmin/people.js';
import './superadmin/features.js';
import './superadmin/pillars.js';
import './superadmin/stakeholders.js';
import './superadmin/config.js';
import './superadmin/audit-errors.js';
import './superadmin/users.js';
import './superadmin/products.js';
import './superadmin/maintenance.js';
import './features/email-composer.js';
import './superadmin/departments.js';
import './superadmin/templates.js';
import './superadmin/all-tasks.js';
import './features/activity.js';
import './features/task-status.js';
import './superadmin/watchdog.js';
import './views/dashboard-charts.js';

// Register all real functions with the global dispatcher
window.__npd_init({
  handleSignIn,
  handleSignOut,
  loadView,
  toggleSidebar:           window.toggleSidebar,
  showCreateProduct:       window.showCreateProduct,
  closeProductModal:       window.closeProductModal,
  saveProduct:             window.saveProduct,
  editProduct:             window.editProduct,
  viewProduct:             window.viewProduct,
  addToAllowlist:          window.addToAllowlist,
  removeFromAllowlist:     window.removeFromAllowlist,
  showToast:               window.showToast,
  calFilterChange:         window.calFilterChange,
  calMove:                 window.calMove,
  calGoToday:              window.calGoToday,
  calDayClick:             window.calDayClick,
  trackerSelectProduct:    window.trackerSelectProduct,
  updatePillarStatus:      window.updatePillarStatus,
  updatePillarNotes:       window.updatePillarNotes,
  showStakeholderConfirm:  window.showStakeholderConfirm,
  toggleStakeholder:       window.toggleStakeholder,
  toggleAllStakeholders:   window.toggleAllStakeholders,
  skipGASSetup:            window.skipGASSetup,
  confirmAndLaunchGAS:     window.confirmAndLaunchGAS,
  triggerDeadlineCheck:    window.triggerDeadlineCheck,
  docsSelectProduct:       window.docsSelectProduct,
  docDragOver:             window.docDragOver,
  docDragLeave:            window.docDragLeave,
  docDrop:                 window.docDrop,
  docFileSelected:         window.docFileSelected,
  generateProgressReport:  window.generateProgressReport,
  showShareModal:          window.showShareModal,
  updateShareAccess:       window.updateShareAccess,
  showWeeklyLog:           window.showWeeklyLog,
  saveWeeklyLog:           window.saveWeeklyLog,
  showHandoverModal:       window.showHandoverModal,
  confirmHandover:         window.confirmHandover,
  reOnboardProduct:        window.reOnboardProduct,
  showSAChallenge:         window.showSAChallenge,
  verifySAPassword:        window.verifySAPassword,
  exitSASession:           window.exitSASession,
  switchSATab:             window.switchSATab,
  saResetUser:             window.saResetUser,
  saClearHandover:         window.saClearHandover,
  saPingGAS:               window.saPingGAS,
  saClearAccessLog:        window.saClearAccessLog,
  clearErrorLog:           window.clearErrorLog,
  toggleFeature:           window.toggleFeature,
  editPillar:              window.editPillar,
  savePillar:              window.savePillar,
  togglePillar:            window.togglePillar,
  deletePillar:            window.deletePillar,
  showAddPillar:           window.showAddPillar,
  addNewPillar:            window.addNewPillar,
  editStakeholder:         window.editStakeholder,
  saveStakeholder:         window.saveStakeholder,
  deleteStakeholder:       window.deleteStakeholder,
  showAddStakeholder:      window.showAddStakeholder,
  addNewStakeholder:       window.addNewStakeholder,
  saveSystemConfig:        window.saveSystemConfig,
  resetAllConfig:          window.resetAllConfig,
  exportAllData:           window.exportAllData,
  clearAuditLog:           window.clearAuditLog,
  saToggleRole:            window.saToggleRole,
  saToggleProductStatus:   window.saToggleProductStatus,
  dashNavToTracker:        window.dashNavToTracker,
  openDrill:               window.openDrill,
  openProjectDashboard:    window.openProjectDashboard,
  depMapNodeClick:         window.depMapNodeClick,
  exportProjectTracker:    window.exportProjectTracker,
  syncProjectSheet:        window.syncProjectSheet,
  copyExportLink:          window.copyExportLink,
  openTaskFromDrill:       window.openTaskFromDrill,
  scrollToDept:            window.scrollToDept,
  showReminderModal:       window.showReminderModal,
  sendReminder:            window.sendReminder,
  setCalView:              window.setCalView,
  setGanttMonths:          window.setGanttMonths,
  selectTemplate:          window.selectTemplate,
  addNewTaskRow:           window.addNewTaskRow,
  removeEditingTask:       window.removeEditingTask,
  updateEditingTask:       window.updateEditingTask,
  updateEditingTaskPreds:  window.updateEditingTaskPreds,
  saveAsTemplatePrompt:    window.saveAsTemplatePrompt,
  showAddTaskToProduct:    window.showAddTaskToProduct,
  addTaskToProduct:        window.addTaskToProduct,
  setTrackerView:          window.setTrackerView,
  moveKanbanTask:          window.moveKanbanTask,
  kbDragStart:             window.kbDragStart,
  kbDrop:                  window.kbDrop,
  editDepartment:          window.editDepartment,
  saveDepartment:          window.saveDepartment,
  deleteDepartment:        window.deleteDepartment,
  showAddDepartment:       window.showAddDepartment,
  addNewDepartment:        window.addNewDepartment,
  previewTemplate:         window.previewTemplate,
  deleteTemplate:          window.deleteTemplate,
  saEditTask:              window.saEditTask,
  saeSaveTask:             window.saeSaveTask,
  showProductActivity:     window.showProductActivity,
  showQuickUpdate:         window.showQuickUpdate,
  quickSetStatus:          window.quickSetStatus,
  dismissWelcome:          window.dismissWelcome,
  generateGCCOLink:        window.generateGCCOLink,
  copyGCCOLink:            window.copyGCCOLink,
  postProductComment:      window.postProductComment,
  quickSaveNote:           window.quickSaveNote,
  saToggleStakeholder:     window.saToggleStakeholder,
  saEditStakeholder:       window.saEditStakeholder,
  saSaveStakeholder:       window.saSaveStakeholder,
  saAddStakeholder:        window.saAddStakeholder,
  saConfirmAddStakeholder: window.saConfirmAddStakeholder,
  editPreferredName:       window.editPreferredName,
  savePreferredName:       window.savePreferredName,
  cancelPreferredName:     window.cancelPreferredName,
  addCustomOnboardEmail:   window.addCustomOnboardEmail,
  removeCustomOnboardEmail: window.removeCustomOnboardEmail,
  updateTaskOwnerDept:     window.updateTaskOwnerDept,
  updateAddTaskIndividuals: window.updateAddTaskIndividuals,
  addNewTaskOwnerChip:     window.addNewTaskOwnerChip,
  removeAtOwner:           window.removeAtOwner,
  addTaskOwner:            window.addTaskOwner,
  removeTaskOwner:         window.removeTaskOwner,
  updateAddIndividuals:    window.updateAddIndividuals,
  saAddStakeholderInDept:  window.saAddStakeholderInDept,
  addStandaloneTask:       window.addStandaloneTask,
  showImportScreen:        window.showImportScreen,
  cycleTaskVisibility:     window.cycleTaskVisibility,
  runAIDiagnostic:         window.runAIDiagnostic,
  clearTaskAck:            window.clearTaskAck,
  lockAllTasksToPrivate:   window.lockAllTasksToPrivate,
  openAllTasksToDept:      window.openAllTasksToDept,
  toggleAskItem:           window.toggleAskItem,
  askSelectAll:            window.askSelectAll,
  submitAsk:               window.submitAsk,
  clearAskHistory:         window.clearAskHistory,
  parseImportSheet:        window.parseImportSheet,
  handleImportFile:        window.handleImportFile,
  confirmImportTasks:      window.confirmImportTasks,
  toggleStandaloneTask:    window.toggleStandaloneTask,
  deleteStandaloneTask:    window.deleteStandaloneTask,
  submitAccessRequest:     window.submitAccessRequest,
  approveAccessRequest:    window.approveAccessRequest,
  denyAccessRequest:       window.denyAccessRequest,
  confirmDeptSelection:    window.confirmDeptSelection,
  saChangeDept:            window.saChangeDept,
  saUnlockDept:            window.saUnlockDept,
  setItemType:             window.setItemType,
  setProductFilter:        window.setProductFilter,
  setStep1Type:            window.setStep1Type,
  convertItemType:         window.convertItemType,
  spinOutTask:             window.spinOutTask,
  setSoType:               window.setSoType,
  confirmSpinOut:          window.confirmSpinOut,
  showReassignTask:        window.showReassignTask,
  updateReassignIndividuals: window.updateReassignIndividuals,
  confirmReassign:         window.confirmReassign,
  saveEmailSchedule:       window.saveEmailSchedule,
  sendMyTodoNow:           window.sendMyTodoNow,
  showAddDocFolder:        window.showAddDocFolder,
  confirmAddDocFolder:     window.confirmAddDocFolder,
  showTaskHistory:         window.showTaskHistory,
  showEmailPreview:        window.showEmailPreview,
  renderDashboardEmailPage: window.renderDashboardEmailPage,
  exportActivityLogPDF:    window.exportActivityLogPDF,
  saDeleteActivity:        window.saDeleteActivity,
  runWatchdogScan:         window.runWatchdogScan,
  watchdogFixGhost:        window.watchdogFixGhost,
  watchdogFixSchema:       window.watchdogFixSchema,
  watchdogSyncCache:       window.watchdogSyncCache,
  watchdogWipeLinks:       window.watchdogWipeLinks,
  watchdogArchiveProd:     window.watchdogArchiveProd,
});

/* ── Auth wiring, deliberately last ──────────────────────────
   Everything above is now defined. Safe for the callback to fire. */
onAuthStateChanged(auth, handleAuthStateChange);
